# Site settings
title: Jaejin Lee
email: jaejinl2@illinois.edu
description: > # this means to ignore newlines until "baseurl:"
  Jaejin Lee. PhD student in Finance. University of Illinois at Urbana-Champaign
# baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://jaejinlee.net" # the base hostname & protocol for your site
googlescholar: #https://scholar.google.com/citations?user=wlRQLtwAAAAJ&hl=en
orcid: #https://orcid.org/0000-0002-2462-0269
github_username:  jaejinleefinance
permalink: /blog/:year/:month/:title.html
gems:
  - jekyll-sitemap

# Build settings
markdown: kramdown
